name = "Laputa Werkstatt - Build Team"
author = "Laputa Werkstatt"
version = "1.0.0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa458008e59ee8c262069e2dc8027a6451e8d926d122795293cf3a69fa7c0441"
