#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 19 09:58:09 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Solas Shader V3.2.zip
